### PR TITLE
Default action of Enter and ShiftEnter should be always prevented

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Default action of `Enter` event should be always prevented. Closes ckeditor/ckeditor5#1120.

### CODE REVIEW

**Comment by pomek** [comment]
I tried to write an integration test in image package but it always passed...

I wanted to fire the `enter` event on `view.document`. Was it a correct way?

**Comment by Reinmar** [comment]
> I wanted to fire the enter event on view.document. Was it a correct way?

Yes.

**Comment by pomek** [comment]
The tests are here - https://github.com/ckeditor/ckeditor5-image/pull/218

But as I said, I am not sure about them.

**Comment by Reinmar** [comment]
You wrote that they always passed. That indeed makes them invalid. I'll look into this.

**Comment by Reinmar** [comment]
OK, I realised now that you're talking about the integration tests. They indeed check a different thing. I'll comment that in that other PR.

**Comment by Reinmar** [comment]
I merged this PR because itself it's correct.

**Pull request merged**
