### PR TITLE
Changed the way EnterObserver handles keydown event

### LINKED ISSUE #753: Image is removed after deleting the block element
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Select the block quote.
3. Press <kbd>Backspace</kbd> twice.

## ✅ Expected result

Only the block quote should be removed.

## ❎ Actual result

The image has been removed.

## 📃 Other details that might be useful

**Notes**

It's a regression.

**GIF**
bug_cke5

**Other information**
OS: Windows 10, MacOS X
Browser: All browsers

### PR DESCRIPTION
**Pull request by szymonkups**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: `EnterObserver` is now stopping generic `keydown` event when handling <kbd>Enter</kbd> key. It fires specific `keydown:enter` event instead. Closes https://github.com/ckeditor/ckeditor5/issues/753.

---
Plese close together with: https://github.com/ckeditor/ckeditor5-typing/pull/132.

### CODE REVIEW

**Comment by Reinmar** [comment]
```
Module not found: Error: Can't resolve '../../ckeditor5-utils/src/priorities' in '/home/travis/build/ckeditor/ckeditor5-enter/tests'```

**Comment by Reinmar** [comment]
One more thing will be removing the `enter` and `delete` events now cause they still cause the same problem – there's `delete` and `keydown:delete` so a listener on `keydown:delete` might be called even if `delete` was stopped.

However, I've got to say that I don't like deleting these two events because it feels right for me to have a higher level input events. E.g. while `delete` might be also triggered by `beforeInput`, it would be odd to trigger `keydown:delete` by `beforeInput`. Which made me uncertain again whether this is the right direction ;/

**Comment by Reinmar** [comment]
> However, I've got to say that I don't like deleting these two events because it feels right for me to have a higher level input events. E.g. while delete might be also triggered by beforeInput, it would be odd to trigger keydown:delete by beforeInput. Which made me uncertain again whether this is the right direction ;/

Yeah, this is a deal breaker for me. The idea behind higher-level `enter` and `delete` events was that they should be a facade over the complexity of lower-level native events. We still need those lower level ones but we need a space for higher-level, feature-oriented events like the ones we were about to remove.

**Comment by szymonkups** [comment]
Closing this PR as we decided to go different way with this issue.

**Pull request closed without merging**
